### Добавить одного пользователя
POST http://localhost:8080/api/users/registration
Content-Type: application/json

{
  "name": "Andrew",
  "password": "password"
}

### Добавить уже существующего пользователя
POST http://localhost:8080/api/users/registration
Content-Type: application/json

{
  "name": "Andrew",
  "password": "password"
}