### Добавить одного пользователя
POST http://localhost:8080/api/users/registration
Content-Type: application/json

{
  "name": "Саша",
  "email": "andrus44ka@gmail.com",
  "password": "password"
}

### Добавить уже существующего пользователя
POST http://localhost:8080/api/users/registration
Content-Type: application/json

{
  "name": "Andrew",
  "email": "andrew@mail.com",
  "password": "password"
}

###
GET http://localhost:8080/api/users?userId=1
